
seed: 0
debug: False
silent: False
device: cuda

max_iters: 1000000
log_interval: 100
val_interval: 5000
model_save_pt: 5000

lr: 1e-5
batch_size: 32
val_steps: 500
grad_clip: 100.
early_stop_patience: 20000
early_stop_key: "loss/total_edit_val"
dropout: 0.0
results_dir: null

eval_only: False
half: False
save: False

model:
  pt: null

data:
  path: null

eval:
  verbose: True
  log_interval: 100
  final_eval: True

hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d_%H-%M-%S_%f${uuid:}}
  sweep:
    dir: ./outputs/${now:%Y-%m-%d_%H-%M-%S_%f}
    subdir: ${hydra.job.num}